export const atributosCliente = [
  {
    id: "name",
    name: "name",
    type: "text",
    placeholder: "Nombre",
    required: true,
  },
  {
    id: "lastname",
    name: "lastname",
    type: "text",
    placeholder: "Apellido",
    required: true,
  },
  {
    id: "dni",
    name: "dni",
    type: "number",
    placeholder: "DNI",
    required: true,
  },
  {
    id: "gender",
    name: "gender",
    type: "select",
    placeholder: "Género",
    required: true,
    options: [
      { value: "", label: "Genero" },
      { value: "HOMBRE", label: "Masculino" },
      { value: "MUJER", label: "Femenino" },
    ],
  },
  {
    id: "email",
    name: "email",
    type: "email",
    placeholder: "Email",
    required: true,
  },
  {
    id: "phone",
    name: "phone",
    type: "number",
    placeholder: "Teléfono",
    required: true,
  },
  {
    id: "date_of_birth",
    name: "date_of_birth",
    type: "date",
    placeholder: "Fecha de nacimiento",
    required: true,
  },
  {
    id: "address",
    name: "address",
    type: "text",
    placeholder: "Calle",
    required: true,
  },
  {
    id: "number",
    name: "number",
    type: "number",
    placeholder: "Número",
    required: true,
  },
  { id: "floor", name: "floor", type: "number", placeholder: "Piso" },
  {
    id: "apartment",
    name: "apartment",
    type: "text",
    placeholder: "Departamento",
  },
  {
    id: "zip_code",
    name: "zip_code",
    type: "number",
    placeholder: "Código Postal",
    required: true,
  },
];
