export const atributosCliente = [
  {
    id: "name",
    name: "name",
    type: "text",
    placeholder: "Nombre",
    required: true,
  },
  {
    id: "lastname",
    name: "lastname",
    type: "text",
    placeholder: "Apellido",
    required: true,
  },
  {
    id: "dni",
    name: "dni",
    type: "number",
    placeholder: "DNI",
    required: true,
  },
  {
    id: "gender",
    name: "gender",
    type: "select",
    placeholder: "Género",
    required: true,
    options: [
      { value: "", label: "Genero" },
      { value: "HOMBRE", label: "Masculino" },
      { value: "MUJER", label: "Femenino" },
    ],
  },
  {
    id: "email",
    name: "email",
    type: "email",
    placeholder: "Email",
    required: true,
  },
  {
    id: "phone",
    name: "phone",
    type: "number",
    placeholder: "Teléfono",
    required: true,
  },
  {
    id: "date_of_birth",
    name: "date_of_birth",
    type: "date",
    placeholder: "Fecha de nacimiento",
    required: true,
  },
  {
    id: "address",
    name: "address",
    type: "text",
    placeholder: "Calle",
    required: true,
  },
  {
    id: "number",
    name: "number",
    type: "number",
    placeholder: "Número",
    required: true,
  },
  { id: "floor", name: "floor", type: "number", placeholder: "Piso" },
  {
    id: "apartment",
    name: "apartment",
    type: "text",
    placeholder: "Departamento",
  },
  {
    id: "zip_code",
    name: "zip_code",
    type: "number",
    placeholder: "Código Postal",
    required: true,
  },
];

export const atributosClienteDelete = ["email", "name", "lastname"];

export const atributosPoliza = [
  {
    id: "dni",
    name: "dni",
    type: "number",
    placeholder: "DNI de la persona",
    required: true,
    disabled: true,
  },
  {
    id: "aseguradora",
    name: "aseguradora",
    type: "text",
    placeholder: "Aseguradora",
    required: true,
  },
  {
    id: "tipoCobertura",
    name: "tipoCobertura",
    type: "select",
    placeholder: "Tipo de Cobertura",
    required: true,
    options: [
      { value: "Tipo de Cobertura", label: "Tipo de Cobertura" },
      {
        value: "Responsabilidad Civil",
        label: "Responsabilidad Civil",
      },
      { value: "Terceros Completo", label: "Terceros Completo" },
      {
        value: "Terceros Completo con Daños Parciales",
        label: "Terceros Completo con Daños Parciales",
      },
      { value: "Todo Riesgo", label: "Todo Riesgo" },
    ],
  },
  {
    id: "primaSegura",
    name: "primaSegura",
    type: "number",
    placeholder: "Prima Segura",
    required: true,
  },
  {
    id: "deducible",
    name: "deducible",
    type: "number",
    placeholder: "Deducible",
    required: true,
  },
  {
    id: "dominio",
    name: "dominio",
    type: "text",
    placeholder: "Dominio",
    required: true,
  },
  {
    id: "marca",
    name: "marca",
    type: "text",
    placeholder: "Marca",
    required: true,
  },
  {
    id: "modelo",
    name: "modelo",
    type: "text",
    placeholder: "Modelo",
    required: true,
  },
  {
    id: "anio",
    name: "anio",
    type: "number",
    placeholder: "Año",
    required: true,
  },
  {
    id: "color",
    name: "color",
    type: "select",
    placeholder: "Color",
    required: true,
    options: [
      { value: "Rojo", label: "Rojo" },
      { value: "Azul", label: "Azul" },
      { value: "Verde", label: "Verde" },
      { value: "Negro", label: "Negro" },
      { value: "Amarillo", label: "Amarillo" },
      { value: "Gris", label: "Gris" },
      { value: "Naranja", label: "Naranja" },
      { value: "Rosa", label: "Rosa" },
      { value: "Marrón", label: "Marrón" },
      { value: "Blanco", label: "Blanco" },
    ],
  },
  {
    id: "tipoVehiculo",
    name: "tipoVehiculo",
    type: "select",
    placeholder: "Tipo de Vehiculo",
    required: true,
    options: [
      { value: "", label: "Tipo de Vehiculo" },
      { value: "AUTO", label: "Auto" },
      { value: "MOTO", label: "Moto" },
      { value: "CAMION", label: "Camion" },
    ],
  },
  {
    id: "numeroIdentificador",
    name: "numeroIdentificador",
    type: "text",
    placeholder: "Numero identificador",
    required: true,
  },
];
